---
title: "Tarefa Aula 1 – Exploração de SNA em R"
date: "Novembro de 2019"

output: 
  word_document: 
    reference_docx: "word-styles-reference.docx"
    toc: yes
---

```{r setup_evaluation, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "./")

# loading required libraries
library(dplyr)
library(lubridate)
library(knitr)
library(stringr)
library(zoo)
library(forecast)
library(ggplot2)
library(ggpubr)
```

# Enunciado (parte 1)

A folha de respostas deverá ter o nome do(s) aluno(s), o cabeçalho de cada questão e as respostas (retirem este trecho de instruções da versão final).

- Explore as rotinas Exemplo Rede.R e Exemplo Rede Two Mode.R . Rode os códigos na plataforma R utilizando como base as tabelas Rede One Mode_Tarefa Aula 1_Berrini T1.xlsx e Rede Two Mode_Tarefa Aula 1_Berrini T1.xlsx. (atenção: não são as mesmas bases trabalhadas em sala). 

- Faça pequenas modificações na tabela e veja seus resultados.

- Inclua outras análises em seu código (usando as extensões sna, network ou igraph) e comente os resultados (seja criativo!).

- Compile as saídas dos códigos (conteúdo das variáveis, gráficos, tabelas) em um documento Word (usando o modelo deste documento) e comente seus resultados (principalmente as medidas de centralidade), análises, potenciais implicações gerenciais, etc, conforme discutido em sala na Aula 1.
